//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 1/12/2010 10:03:34 PM
namespace SubversionStatistics.DataModel
{
    
    /// <summary>
    /// There are no comments for SvnStatEntities in the schema.
    /// </summary>
    public partial class SvnStatEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SvnStatEntities object using the connection string found in the 'SvnStatEntities' section of the application configuration file.
        /// </summary>
        public SvnStatEntities() : 
                base("name=SvnStatEntities", "SvnStatEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SvnStatEntities object.
        /// </summary>
        public SvnStatEntities(string connectionString) : 
                base(connectionString, "SvnStatEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SvnStatEntities object.
        /// </summary>
        public SvnStatEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SvnStatEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for FileDetails in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FileDetails> FileDetails
        {
            get
            {
                if ((this._FileDetails == null))
                {
                    this._FileDetails = base.CreateQuery<FileDetails>("[FileDetails]");
                }
                return this._FileDetails;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FileDetails> _FileDetails;
        /// <summary>
        /// There are no comments for Revision in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Revision> Revision
        {
            get
            {
                if ((this._Revision == null))
                {
                    this._Revision = base.CreateQuery<Revision>("[Revision]");
                }
                return this._Revision;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Revision> _Revision;
        /// <summary>
        /// There are no comments for RevisionDetails in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<RevisionDetails> RevisionDetails
        {
            get
            {
                if ((this._RevisionDetails == null))
                {
                    this._RevisionDetails = base.CreateQuery<RevisionDetails>("[RevisionDetails]");
                }
                return this._RevisionDetails;
            }
        }
        private global::System.Data.Objects.ObjectQuery<RevisionDetails> _RevisionDetails;
        /// <summary>
        /// There are no comments for FileDetails in the schema.
        /// </summary>
        public void AddToFileDetails(FileDetails fileDetails)
        {
            base.AddObject("FileDetails", fileDetails);
        }
        /// <summary>
        /// There are no comments for Revision in the schema.
        /// </summary>
        public void AddToRevision(Revision revision)
        {
            base.AddObject("Revision", revision);
        }
        /// <summary>
        /// There are no comments for RevisionDetails in the schema.
        /// </summary>
        public void AddToRevisionDetails(RevisionDetails revisionDetails)
        {
            base.AddObject("RevisionDetails", revisionDetails);
        }
    }
    /// <summary>
    /// There are no comments for SvnStatModel.FileDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FileID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SvnStatModel", Name="FileDetails")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FileDetails : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FileDetails object.
        /// </summary>
        /// <param name="fileID">Initial value of FileID.</param>
        /// <param name="fileName">Initial value of FileName.</param>
        public static FileDetails CreateFileDetails(long fileID, string fileName)
        {
            FileDetails fileDetails = new FileDetails();
            fileDetails.FileID = fileID;
            fileDetails.FileName = fileName;
            return fileDetails;
        }
        /// <summary>
        /// There are no comments for Property FileID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long FileID
        {
            get
            {
                return this._FileID;
            }
            set
            {
                this.OnFileIDChanging(value);
                this.ReportPropertyChanging("FileID");
                this._FileID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FileID");
                this.OnFileIDChanged();
            }
        }
        private long _FileID;
        partial void OnFileIDChanging(long value);
        partial void OnFileIDChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this.ReportPropertyChanging("FileName");
                this._FileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileName");
                this.OnFileNameChanged();
            }
        }
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
    }
    /// <summary>
    /// There are no comments for SvnStatModel.Revision in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Revision1
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SvnStatModel", Name="Revision")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Revision : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Revision object.
        /// </summary>
        /// <param name="revision1">Initial value of Revision1.</param>
        /// <param name="account">Initial value of Account.</param>
        /// <param name="date">Initial value of Date.</param>
        public static Revision CreateRevision(int revision1, string account, global::System.DateTime date)
        {
            Revision revision = new Revision();
            revision.Revision1 = revision1;
            revision.Account = account;
            revision.Date = date;
            return revision;
        }
        /// <summary>
        /// There are no comments for Property Revision1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Revision1
        {
            get
            {
                return this._Revision1;
            }
            set
            {
                this.OnRevision1Changing(value);
                this.ReportPropertyChanging("Revision1");
                this._Revision1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Revision1");
                this.OnRevision1Changed();
            }
        }
        private int _Revision1;
        partial void OnRevision1Changing(int value);
        partial void OnRevision1Changed();
        /// <summary>
        /// There are no comments for Property Account in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Account
        {
            get
            {
                return this._Account;
            }
            set
            {
                this.OnAccountChanging(value);
                this.ReportPropertyChanging("Account");
                this._Account = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Account");
                this.OnAccountChanged();
            }
        }
        private string _Account;
        partial void OnAccountChanging(string value);
        partial void OnAccountChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    }
    /// <summary>
    /// There are no comments for SvnStatModel.RevisionDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SvnStatModel", Name="RevisionDetails")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RevisionDetails : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new RevisionDetails object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="revision">Initial value of Revision.</param>
        /// <param name="fileID">Initial value of FileID.</param>
        public static RevisionDetails CreateRevisionDetails(long id, int revision, int fileID)
        {
            RevisionDetails revisionDetails = new RevisionDetails();
            revisionDetails.ID = id;
            revisionDetails.Revision = revision;
            revisionDetails.FileID = fileID;
            return revisionDetails;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Revision in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Revision
        {
            get
            {
                return this._Revision;
            }
            set
            {
                this.OnRevisionChanging(value);
                this.ReportPropertyChanging("Revision");
                this._Revision = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Revision");
                this.OnRevisionChanged();
            }
        }
        private int _Revision;
        partial void OnRevisionChanging(int value);
        partial void OnRevisionChanged();
        /// <summary>
        /// There are no comments for Property FileID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int FileID
        {
            get
            {
                return this._FileID;
            }
            set
            {
                this.OnFileIDChanging(value);
                this.ReportPropertyChanging("FileID");
                this._FileID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FileID");
                this.OnFileIDChanged();
            }
        }
        private int _FileID;
        partial void OnFileIDChanging(int value);
        partial void OnFileIDChanged();
    }
}
