//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.225
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nome file originale:
// Data di generazione: 5/4/2011 10:06:47 PM
namespace SubversionStatistics.DataModel
{
    
    /// <summary>
    /// Nessun commento per SvnStatEntities nello schema.
    /// </summary>
    public partial class SvnStatEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inizializza un nuovo oggetto SvnStatEntities utilizzando la stringa di connessione trovata nella sezione 'SvnStatEntities' del file di configurazione dell'applicazione.
        /// </summary>
        public SvnStatEntities() : 
                base("name=SvnStatEntities", "SvnStatEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inizializzare un nuovo oggetto SvnStatEntities.
        /// </summary>
        public SvnStatEntities(string connectionString) : 
                base(connectionString, "SvnStatEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inizializzare un nuovo oggetto SvnStatEntities.
        /// </summary>
        public SvnStatEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SvnStatEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Nessun commento per FileDetails nello schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<FileDetails> FileDetails
        {
            get
            {
                if ((this._FileDetails == null))
                {
                    this._FileDetails = base.CreateQuery<FileDetails>("[FileDetails]");
                }
                return this._FileDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<FileDetails> _FileDetails;
        /// <summary>
        /// Nessun commento per Revision nello schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Revision> Revision
        {
            get
            {
                if ((this._Revision == null))
                {
                    this._Revision = base.CreateQuery<Revision>("[Revision]");
                }
                return this._Revision;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Revision> _Revision;
        /// <summary>
        /// Nessun commento per RevisionDetails nello schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<RevisionDetails> RevisionDetails
        {
            get
            {
                if ((this._RevisionDetails == null))
                {
                    this._RevisionDetails = base.CreateQuery<RevisionDetails>("[RevisionDetails]");
                }
                return this._RevisionDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<RevisionDetails> _RevisionDetails;
        /// <summary>
        /// Nessun commento per FileDetails nello schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToFileDetails(FileDetails fileDetails)
        {
            base.AddObject("FileDetails", fileDetails);
        }
        /// <summary>
        /// Nessun commento per Revision nello schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRevision(Revision revision)
        {
            base.AddObject("Revision", revision);
        }
        /// <summary>
        /// Nessun commento per RevisionDetails nello schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRevisionDetails(RevisionDetails revisionDetails)
        {
            base.AddObject("RevisionDetails", revisionDetails);
        }
    }
    /// <summary>
    /// Nessun commento per SvnStatModel.FileDetails nello schema.
    /// </summary>
    /// <KeyProperties>
    /// FileID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SvnStatModel", Name="FileDetails")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FileDetails : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crea un nuovo oggetto FileDetails.
        /// </summary>
        /// <param name="fileID">Valore iniziale di FileID.</param>
        /// <param name="fileName">Valore iniziale di FileName.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static FileDetails CreateFileDetails(long fileID, string fileName)
        {
            FileDetails fileDetails = new FileDetails();
            fileDetails.FileID = fileID;
            fileDetails.FileName = fileName;
            return fileDetails;
        }
        /// <summary>
        /// Nessun commento per la proprietà FileID nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long FileID
        {
            get
            {
                return this._FileID;
            }
            set
            {
                this.OnFileIDChanging(value);
                this.ReportPropertyChanging("FileID");
                this._FileID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FileID");
                this.OnFileIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _FileID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileIDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileIDChanged();
        /// <summary>
        /// Nessun commento per la proprietà FileName nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this.ReportPropertyChanging("FileName");
                this._FileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileName");
                this.OnFileNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _FileName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileNameChanged();
    }
    /// <summary>
    /// Nessun commento per SvnStatModel.Revision nello schema.
    /// </summary>
    /// <KeyProperties>
    /// Revision1
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SvnStatModel", Name="Revision")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Revision : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crea un nuovo oggetto Revision.
        /// </summary>
        /// <param name="revision1">Valore iniziale di Revision1.</param>
        /// <param name="account">Valore iniziale di Account.</param>
        /// <param name="date">Valore iniziale di Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Revision CreateRevision(int revision1, string account, global::System.DateTime date)
        {
            Revision revision = new Revision();
            revision.Revision1 = revision1;
            revision.Account = account;
            revision.Date = date;
            return revision;
        }
        /// <summary>
        /// Nessun commento per la proprietà Revision1 nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Revision1
        {
            get
            {
                return this._Revision1;
            }
            set
            {
                this.OnRevision1Changing(value);
                this.ReportPropertyChanging("Revision1");
                this._Revision1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Revision1");
                this.OnRevision1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Revision1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRevision1Changing(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRevision1Changed();
        /// <summary>
        /// Nessun commento per la proprietà Account nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Account
        {
            get
            {
                return this._Account;
            }
            set
            {
                this.OnAccountChanging(value);
                this.ReportPropertyChanging("Account");
                this._Account = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Account");
                this.OnAccountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Account;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAccountChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAccountChanged();
        /// <summary>
        /// Nessun commento per la proprietà Date nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDateChanged();
    }
    /// <summary>
    /// Nessun commento per SvnStatModel.RevisionDetails nello schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SvnStatModel", Name="RevisionDetails")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RevisionDetails : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crea un nuovo oggetto RevisionDetails.
        /// </summary>
        /// <param name="id">Valore iniziale di ID.</param>
        /// <param name="revision">Valore iniziale di Revision.</param>
        /// <param name="fileID">Valore iniziale di FileID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static RevisionDetails CreateRevisionDetails(long id, int revision, int fileID)
        {
            RevisionDetails revisionDetails = new RevisionDetails();
            revisionDetails.ID = id;
            revisionDetails.Revision = revision;
            revisionDetails.FileID = fileID;
            return revisionDetails;
        }
        /// <summary>
        /// Nessun commento per la proprietà ID nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// Nessun commento per la proprietà Revision nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Revision
        {
            get
            {
                return this._Revision;
            }
            set
            {
                this.OnRevisionChanging(value);
                this.ReportPropertyChanging("Revision");
                this._Revision = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Revision");
                this.OnRevisionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Revision;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRevisionChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRevisionChanged();
        /// <summary>
        /// Nessun commento per la proprietà FileID nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int FileID
        {
            get
            {
                return this._FileID;
            }
            set
            {
                this.OnFileIDChanging(value);
                this.ReportPropertyChanging("FileID");
                this._FileID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FileID");
                this.OnFileIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _FileID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileIDChanged();
    }
}
